"""
Reference Voice Library
=====================================

Experiment 9-5 in the book uses Fish Audio's voice cloning: prepare 24 different
reference voices for the same virtual persona (emotion 4 × speed 3 × style 2), the execution layer selects the best matching reference voice based on control markers, and Fish Audio ensures "timbre consistency" across different reference voices, with only prosody and emotion varying.

Since Fish Audio key is unavailable, this project uses OpenAI TTS to demonstrate the same approach:
  - "Timbre consistency" -> the entire library uses a fixed base voice (e.g., alloy) to keep timbre unchanged;
  - "Prosody/emotion variation" -> each reference voice corresponds to a different set of instructions (style prompts),
                       gpt-4o-mini-tts changes tone, speed, and emotion accordingly.

Thus, a "reference voice" here = a (base_voice + instructions[+speed_factor]) profile for each (emotion × speed × style) combination. The entire library is generated by the Cartesian product of dimensions.
"""

# ---------------------------------------------------------------------------
# Values of the three control dimensions, and the corresponding Chinese instruction fragments for each value
# ---------------------------------------------------------------------------

# Emotion dimension: control markers [EMO:x] / [情感=x]
# Consistent with the four emotions listed in Experiment 9-5: neutral / happy / frustrated / thinking
EMOTIONS = {
    "neutral":    " Tone calm, neutral, without obvious emotion",
    "happy":      " Tone cheerful, rising, with a hint of smile",
    "frustrated": " Tone low, slightly tired and resigned",
    "thinking":   " Tone hesitant, thoughtful, with slight hesitation and pause",
}

# Speed dimension: control markers [SPEED:x] / [语速=x]
SPEEDS = {
    "normal": (" Normal speed",       1.0),
    "fast":   (" Slightly fast, crisp and clear", 1.25),
    "slow":   (" Slightly slow, unhurried",   0.80),
}

# Style dimension: control markers [STYLE:x] / [风格=x]
STYLES = {
    "formal": " Use a formal, professional customer service tone",
    "casual": " Use a relaxed, friendly, conversational tone",
}

# Unified base voice for the entire library — used to simulate Fish Audio's "timbre consistency"
BASE_VOICE = "alloy"

# Instructions fragment appended for emphasis ([强调].../<emphasis>...)
EMPHASIS_HINT = " And emphasize key information in the sentence, highlighting it"


def build_instructions(emotion: str, speed: str, style: str, emphasis: bool = False) -> str:
    """ Combine the three dimensions into a single gpt-4o-mini-tts instructions (style prompt)."""
    emo = EMOTIONS.get(emotion, EMOTIONS["neutral"])
    spd = SPEEDS.get(speed, SPEEDS["normal"])[0]
    sty = STYLES.get(style, STYLES["formal"])
    text = f" Please read in Chinese.{sty}，{emo}，{spd}。"
    if emphasis:
        text += EMPHASIS_HINT + "。"
    return text


def speed_factor(speed: str) -> float:
    """ Speed multiplier, only used as speed parameter in the tts-1 fallback path (which does not support instructions)."""
    return SPEEDS.get(speed, SPEEDS["normal"])[1]


def profile_key(emotion: str, speed: str, style: str) -> str:
    return f"{emotion}_{speed}_{style}"


def build_voice_library() -> dict:
    """ Generate the complete reference voice library: Cartesian product of emotion × speed × style."""
    lib = {}
    for emotion in EMOTIONS:
        for speed in SPEEDS:
            for style in STYLES:
                key = profile_key(emotion, speed, style)
                lib[key] = {
                    "emotion": emotion,
                    "speed": speed,
                    "style": style,
                    "base_voice": BASE_VOICE,
                    "instructions": build_instructions(emotion, speed, style),
                    "speed_factor": speed_factor(speed),
                }
    return lib


VOICE_LIBRARY = build_voice_library()


if __name__ == "__main__":
    print(f" The reference voice library has a total of {len(VOICE_LIBRARY)} entries (emotion {len(EMOTIONS)} × speed "
          f"{len(SPEEDS)} × style {len(STYLES)}), all with fixed base voice = {BASE_VOICE}")
    for k, v in list(VOICE_LIBRARY.items())[:6]:
        print(f"  {k:28s} -> {v['instructions']}")
    print("  ...")
