"""
Experiment 5-10: Command-line entry for an ERP Agent with natural language interaction (NL -> SQL, artifact mode).

Core idea (artifact mode): The Agent is only responsible for "generating SQL artifacts", not for moving data itself;
the actual query is executed by the system using the generated SQL against the database, and the result table is delivered directly to the user interface.

Subcommands:
  run     Online: Agent generates SQL -> execute -> compare with reference implementation (requires OPENAI_API_KEY, default subcommand)
  gold    Offline: Execute built-in "standard SQL" for 10 questions -> compare with reference implementation (no API needed, for self-check/demo)
  ask     Online: Single natural language query -> generate SQL -> execute and print result table (requires OPENAI_API_KEY)
  initdb  Create tables and load reproducible seed data into a SQLite file (offline, convenient for manual inspection with sqlite3)

When no subcommand is given, it is equivalent to `run`, maintaining the same default behavior as the old `python demo.py`.
Full usage see `python demo.py --help`, or for a subcommand `python demo.py <subcommand> --help`.
"""

import argparse
import json
import os
import sqlite3
import sys
from datetime import date

try:
    from dotenv import load_dotenv
    load_dotenv()
except Exception:
    pass

import seed
import reference
import gold
from questions import QUESTIONS
from agent import SQLAgent, MODEL


# ---------------- Result Comparison ----------------
def _norm(v):
    """Normalize a single value to ('n', numeric) or ('s', string) for tolerance comparison."""
    if isinstance(v, bool):
        return ("n", float(v))
    if isinstance(v, (int, float)):
        return ("n", round(float(v), 2))
    return ("s", str(v).strip())


def _row_match(a, b, tol):
    if len(a) != len(b):
        return False
    for x, y in zip(a, b):
        if x[0] != y[0]:
            return False
        if x[0] == "n":
            if abs(x[1] - y[1]) > tol:
                return False
        else:
            if x[1] != y[1]:
                return False
    return True


def compare(expected, actual, tol=0.1):
    """Compare expected and actual results as multisets (ignoring row order), with tolerance for numeric values."""
    exp = [tuple(_norm(v) for v in r) for r in expected]
    act = [tuple(_norm(v) for v in r) for r in actual]
    if len(exp) != len(act):
        return False, f"Row count mismatch: expected {len(exp)} rows, actual {len(act)} rows"
    remaining = list(act)
    for er in exp:
        for i, ar in enumerate(remaining):
            if _row_match(er, ar, tol):
                remaining.pop(i)
                break
        else:
            return False, f"Missing matching rows:{_readable(er)}"
    return True, "Results match"


def _readable(norm_row):
    return tuple(v[1] for v in norm_row)


# ---------------- Result Table Printing ----------------
def print_table(rows, max_rows=12):
    if not rows:
        print("    (empty result)")
        return
    for r in rows[:max_rows]:
        cells = []
        for v in r:
            if isinstance(v, float):
                cells.append(f"{v:.2f}")
            else:
                cells.append(str(v))
        print("    | " + " | ".join(cells) + " |")
    if len(rows) > max_rows:
        print(f"    ... total {len(rows)} rows")


# ---------------- Main Loop for Per-Question Execution (shared online/offline) ----------------
def run_questions(conn, employees, salaries, today, sql_provider,
                  qids=None, print_sql=True, max_rows=12):
    """For each question: get SQL -> execute -> compare with Python reference implementation, print per question.

    sql_provider(q) -> str: provides the SQL for the question; may throw an exception (e.g., online LLM call failure).
      Online mode passes `lambda q: agent.generate_sql(q["nl"], q["hint"])`,
      Offline mode passes `lambda q: gold.GOLD[q["id"]]`.
    qids: only run these question IDs (None means all).
    Returns (passed, total, results), where results is a dict of per-question details, convenient for --output export.
    """
    results = []
    passed = 0
    total = 0
    for q in QUESTIONS:
        if qids and q["id"] not in qids:
            continue
        total += 1
        qid, nl, hint = q["id"], q["nl"], q["hint"]
        print(f"\n[Question {qid}】{nl}")
        rec = {"id": qid, "nl": nl, "sql": None, "rows": None,
               "passed": False, "error": None}

        # 1) Get SQL artifact (online: generated by Agent, offline: built-in gold SQL)
        try:
            sql = sql_provider(q)
        except Exception as e:
            print(f"  [SQL generation failed] {e}")
            rec["error"] = f"SQL generation failed:{e}"
            results.append(rec)
            continue
        rec["sql"] = sql
        if print_sql:
            print("  Generated SQL:")
            for line in sql.splitlines():
                print("    " + line)

        # 2) System executes SQL
        try:
            cur = conn.cursor()
            cur.execute(sql)
            actual = cur.fetchall()
        except Exception as e:
            print(f"  [SQL execution error] {e}")
            print("  Result: Fail ✗")
            rec["error"] = f"SQL execution error:{e}"
            results.append(rec)
            continue
        rec["rows"] = [list(r) for r in actual]

        print("  Query result:")
        print_table(actual, max_rows=max_rows)

        # 3) Compare with reference implementation
        expected = reference.REFERENCE[qid](employees, salaries, today)
        ok, msg = compare(expected, actual)
        rec["passed"] = ok
        if ok:
            passed += 1
            print(f"  Check: Pass ✓ ({msg}）")
        else:
            print(f"  Check: Fail ✗ ({msg}）")
            print(f"       Reference expected:{[tuple(r) for r in expected][:12]}")
        results.append(rec)

    return passed, total, results


# ---------------- Common: Database creation, question ID filtering, export, header/footer ----------------
def _build_db(db_path, today):
    """Generate data with a fixed seed and load into the specified SQLite database (':memory:' or file path).

    Reload each time to ensure strict alignment with expected answers in reference.py and reproducible results.
    """
    employees, salaries = seed.generate(today)
    conn = sqlite3.connect(db_path)
    seed.create_db(conn, employees, salaries)
    return conn, employees, salaries


def _parse_only(only):
    """Parse '1,5,10' into {1,5,10}; empty/None means all questions."""
    if not only:
        return None
    ids = set()
    for part in only.split(","):
        part = part.strip()
        if part:
            ids.add(int(part))
    unknown = ids - {q["id"] for q in QUESTIONS}
    if unknown:
        raise SystemExit(f"Unknown question number: {sorted(unknown)}(Valid question numbers 1~{len(QUESTIONS)}）")
    return ids


def _header(mode, today, employees, salaries, model=None):
    print("=" * 70)
    tail = f"  |  Model: {model}" if model else "  |  Offline (no API call)"
    print(f"ERP Agent Experiment 5-10  |  {mode}{tail}")
    print(f"Today: {today.isoformat()}  |  Employees {len(employees)} people,"
          f"Payroll records {len(salaries)} entries")
    print("=" * 70)


def _footer(passed, total):
    print("\n" + "=" * 70)
    rate = (passed / total * 100) if total else 0
    print(f"Overall pass rate: {passed}/{total}  ({rate:.0f}%)")
    print("=" * 70)


def _write_output(path, mode, today, passed, total, results):
    payload = {
        "experiment": "5-10 ERP Agent NL->SQL",
        "mode": mode,
        "date": today.isoformat(),
        "passed": passed,
        "total": total,
        "results": results,
    }
    with open(path, "w", encoding="utf-8") as f:
        json.dump(payload, f, ensure_ascii=False, indent=2)
    print(f"\nResult JSON written:{path}")


def _require_api():
    if not (os.environ.get("OPENAI_API_KEY") or os.environ.get("OPENROUTER_API_KEY")):
        print("Please set the OPENAI_API_KEY (or OPENROUTER_API_KEY as fallback) environment variable (you can copy env.example to .env).")
        print("To run offline without API calls, use: python demo.py gold")
        sys.exit(1)


# ---------------- Subcommands ----------------
def cmd_run(args):
    """Online: Agent generates SQL -> executes -> compares."""
    _require_api()
    today = date.today()
    conn, emps, sals = _build_db(args.db, today)
    model = args.model or os.environ.get("OPENAI_MODEL", MODEL)
    _header("Online (Agent generates SQL)", today, emps, sals, model=model)
    agent = SQLAgent(model=model)
    qids = _parse_only(args.only)
    passed, total, results = run_questions(
        conn, emps, sals, today,
        sql_provider=lambda q: agent.generate_sql(q["nl"], q["hint"]),
        qids=qids, max_rows=args.max_rows,
    )
    _footer(passed, total)
    if args.output:
        _write_output(args.output, "run", today, passed, total, results)


def cmd_gold(args):
    """Offline: Executes built-in standard SQL -> compares (no API needed)."""
    today = date.today()
    conn, emps, sals = _build_db(args.db, today)
    _header("Offline self-check (built-in gold SQL)", today, emps, sals, model=None)
    qids = _parse_only(args.only)
    passed, total, results = run_questions(
        conn, emps, sals, today,
        sql_provider=lambda q: gold.GOLD[q["id"]],
        qids=qids, max_rows=args.max_rows,
    )
    _footer(passed, total)
    if args.output:
        _write_output(args.output, "gold", today, passed, total, results)


def cmd_ask(args):
    """Online: Single natural language query -> generates SQL -> executes and prints result table."""
    _require_api()
    today = date.today()
    conn, emps, sals = _build_db(args.db, today)
    model = args.model or os.environ.get("OPENAI_MODEL", MODEL)
    agent = SQLAgent(model=model)
    hint = args.hint or "Determine the columns to return yourself; output only one SELECT."
    print(f"[Question]{args.query}")
    try:
        sql = agent.generate_sql(args.query, hint)
    except Exception as e:
        print(f"[Agent failed to generate SQL] {e}")
        sys.exit(1)
    print("Generated SQL: ")
    for line in sql.splitlines():
        print("  " + line)
    try:
        cur = conn.cursor()
        cur.execute(sql)
        rows = cur.fetchall()
    except Exception as e:
        print(f"[SQL execution error] {e}")
        sys.exit(1)
    print("Query result: ")
    print_table(rows, max_rows=args.max_rows)


def cmd_initdb(args):
    """Create a table and seed data into a SQLite file for manual inspection with sqlite3."""
    today = date.today()
    if args.db == ":memory:":
        raise SystemExit("initdb requires a file path, e.g.: python demo.py initdb --db erp.db")
    if os.path.exists(args.db):
        os.remove(args.db)
    conn, emps, sals = _build_db(args.db, today)
    conn.close()
    print(f"Written to SQLite database: {args.db}")
    print(f"  Employee {len(emps)} person, salary record {len(sals)} entries, base date {today.isoformat()}")
    print(f"  Manual view: sqlite3 {args.db} \"SELECT * FROM employees LIMIT 5;\"")
    print(f"  Offline re-run: python demo.py gold --db {args.db}")


# ---------------- argparse CLI ----------------
def build_parser():
    p = argparse.ArgumentParser(
        prog="demo.py",
        description="Experiment 5-10: Natural Language Interaction ERP Agent (NL -> SQL, artifact mode)",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="Without a subcommand, equivalent to run (preserving old default behavior)."
               "Offline self-check does not require API: python demo.py gold",
    )
    sub = p.add_subparsers(dest="cmd", metavar="Subcommands")

    def add_common(sp, with_model=False):
        sp.add_argument("--db", default=":memory:",
                        help="SQLite database: ':memory:' (default, in-memory) or file path")
        sp.add_argument("--only", default=None, metavar="Question number list",
                        help="Run only specified question numbers, comma-separated, e.g., 1,5,10 (default all)")
        sp.add_argument("--max-rows", type=int, default=12, dest="max_rows",
                        help="Maximum number of rows to print per result table (default 12)")
        sp.add_argument("--output", default=None, metavar="Path",
                        help="Write per-question results to a JSON file")
        if with_model:
            sp.add_argument("--model", default=None,
                            help=f"Override model (default reads OPENAI_MODEL, otherwise {MODEL}）")

    sp_run = sub.add_parser("run", help="Online: Agent generates SQL, runs 10 questions and validates (requires API)")
    add_common(sp_run, with_model=True)
    sp_run.set_defaults(func=cmd_run)

    sp_gold = sub.add_parser("gold", help="Offline: Execute built-in standard SQL, runs 10 questions and validates (no API required)")
    add_common(sp_gold, with_model=False)
    sp_gold.set_defaults(func=cmd_gold)

    sp_ask = sub.add_parser("ask", help="Online: Single natural language query -> SQL -> result table (requires API)")
    sp_ask.add_argument("query", help="Natural language question to query, e.g., \"How many current employees are in the R&D department?\"")
    sp_ask.add_argument("--hint", default=None, help="Optional: Supplement business scope/expected return columns")
    sp_ask.add_argument("--db", default=":memory:",
                        help="SQLite database: ':memory:' (default) or file path")
    sp_ask.add_argument("--max-rows", type=int, default=20, dest="max_rows",
                        help="Maximum number of rows to print in result table (default 20)")
    sp_ask.add_argument("--model", default=None,
                        help=f"Override model (default reads OPENAI_MODEL, otherwise {MODEL}）")
    sp_ask.set_defaults(func=cmd_ask)

    sp_init = sub.add_parser("initdb", help="Create table and seed data into SQLite file (offline)")
    sp_init.add_argument("--db", default="erp.db",
                         help="Target SQLite file path (default erp.db)")
    sp_init.set_defaults(func=cmd_initdb)

    return p


def main(argv=None):
    parser = build_parser()
    args = parser.parse_args(argv)
    if args.cmd is None:
        #  Without subcommand -> use old default behavior: run all 10 questions online
        args = parser.parse_args((argv or []) + ["run"])
    args.func(args)


if __name__ == "__main__":
    main()
