"""
10 "gold SQL" queries (SQLite dialect), manually written and verified one by one.

Purpose:
  - Offline demo (`python demo.py gold`): execute these SQL queries without calling any API,
    proving that the schema + seed data model is self-consistent and queryable;
  - As a "reference implementation" for SQL generated by the Agent: semantically consistent
    with reference.py (pure Python reference implementation). `demo.py` compares execution
    results with reference.py and prints pass/fail for each query.

Conventions:
  - Dates always use date('now','localtime') / strftime(...,'now','localtime') to get "today",
    aligning with seed.py which uses local date.today() to generate data (avoid UTC vs local one-day difference);
  - **Do not hardcode years**, always derive from current database date using modifiers ('-1 year' / 'start of year' etc.);
  - "Department A" = R&D, "Department B" = Sales; "Active" = leave_date IS NULL.
"""

GOLD = {
    # 1. Average tenure (in days) per employee. Use leave_date for departed, today for active.
    1: """
SELECT ROUND(AVG(
         julianday(COALESCE(leave_date, date('now','localtime')))
         - julianday(hire_date)
       ), 2) AS avg_tenure_days
FROM employees;
""".strip(),

    # 2. Number of active employees per department.
    2: """
SELECT department, COUNT(*) AS active_count
FROM employees
WHERE leave_date IS NULL
GROUP BY department;
""".strip(),

    # 3. Which department (including departed) has the highest average level? Return only department name.
    3: """
SELECT department
FROM employees
GROUP BY department
ORDER BY AVG(level) DESC
LIMIT 1;
""".strip(),

    # 4. Number of new hires per department this year and last year (by hire_date year).
    4: """
SELECT department,
       SUM(CASE WHEN strftime('%Y', hire_date)
                   = strftime('%Y','now','localtime')          THEN 1 ELSE 0 END) AS this_year,
       SUM(CASE WHEN strftime('%Y', hire_date)
                   = strftime('%Y','now','localtime','-1 year') THEN 1 ELSE 0 END) AS last_year
FROM employees
GROUP BY department
HAVING this_year > 0 OR last_year > 0;
""".strip(),

    # 5. Average salary in R&D (Department A) from March of the year before last to May of last year (inclusive).
    5: """
SELECT ROUND(AVG(s.salary), 2) AS avg_salary
FROM salaries s
JOIN employees e ON e.emp_id = s.emp_id
WHERE e.department = 'R&D'
  AND strftime('%Y-%m', s.pay_date) BETWEEN
        strftime('%Y-%m','now','localtime','start of year','-2 years','+2 months')
    AND strftime('%Y-%m','now','localtime','start of year','-1 year','+4 months');
""".strip(),

    # 6. Average salary last year for R&D (A) and Sales (B), two rows (including departed employees).
    6: """
SELECT e.department, ROUND(AVG(s.salary), 2) AS avg_salary
FROM salaries s
JOIN employees e ON e.emp_id = s.emp_id
WHERE e.department IN ('R&D','Sales')
  AND strftime('%Y', s.pay_date) = strftime('%Y','now','localtime','-1 year')
GROUP BY e.department;
""".strip(),

    # 7. Average salary per level this year.
    7: """
SELECT e.level, ROUND(AVG(s.salary), 2) AS avg_salary
FROM salaries s
JOIN employees e ON e.emp_id = s.emp_id
WHERE strftime('%Y', s.pay_date) = strftime('%Y','now','localtime')
GROUP BY e.level;
""".strip(),

    # 8. Tenure buckets (within 1 year / 1-2 years / 2-3 years, ignore >3 years): average of latest month's salary per bucket.
    8: """
WITH latest AS (          -- latest month salary per employee
  SELECT s.emp_id, s.salary
  FROM salaries s
  JOIN (SELECT emp_id, MAX(pay_date) AS mp FROM salaries GROUP BY emp_id) m
    ON m.emp_id = s.emp_id AND m.mp = s.pay_date
),
bucketed AS (             -- assign tenure bucket to each employee
  SELECT e.emp_id,
         CASE
           WHEN julianday(date('now','localtime')) - julianday(e.hire_date) < 365  THEN 'Within one year'
           WHEN julianday(date('now','localtime')) - julianday(e.hire_date) < 730  THEN 'One to two years'
           WHEN julianday(date('now','localtime')) - julianday(e.hire_date) < 1095 THEN 'Two to three years'
           ELSE NULL
         END AS bucket
  FROM employees e
)
SELECT b.bucket, ROUND(AVG(l.salary), 2) AS avg_salary
FROM bucketed b
JOIN latest l ON l.emp_id = b.emp_id
WHERE b.bucket IS NOT NULL
GROUP BY b.bucket;
""".strip(),

    # 9. Top 10 employees with largest salary increase from last year to this year (avg salary this year - avg salary last year), only those with salary in both years.
    9: """
WITH ty AS (
  SELECT emp_id, AVG(salary) AS a FROM salaries
  WHERE strftime('%Y', pay_date) = strftime('%Y','now','localtime')          GROUP BY emp_id),
ly AS (
  SELECT emp_id, AVG(salary) AS a FROM salaries
  WHERE strftime('%Y', pay_date) = strftime('%Y','now','localtime','-1 year') GROUP BY emp_id)
SELECT e.name, ROUND(ty.a - ly.a, 2) AS raise_amt
FROM ty
JOIN ly ON ty.emp_id = ly.emp_id
JOIN employees e ON e.emp_id = ty.emp_id
ORDER BY raise_amt DESC
LIMIT 10;
""".strip(),

    # 10. Salary arrears: active in a month but no salary record. Recursively expand each employee's active months and left join salary table.
    10: """
WITH RECURSIVE em(emp_id, m, end_m) AS (
  SELECT emp_id,
         strftime('%Y-%m', hire_date),
         COALESCE(strftime('%Y-%m', leave_date), strftime('%Y-%m','now','localtime'))
  FROM employees
  UNION ALL
  SELECT emp_id, strftime('%Y-%m', date(m || '-01', '+1 month')), end_m
  FROM em WHERE m < end_m)
SELECT em.emp_id, em.m
FROM em
LEFT JOIN salaries s
       ON s.emp_id = em.emp_id AND strftime('%Y-%m', s.pay_date) = em.m
WHERE s.emp_id IS NULL;
""".strip(),
}
