"""
Generate reproducible ERP seed data (employee table + salary table).

Design points (ensure all 10 questions have deterministic answers):
- About 40 employees across 5 departments and multiple levels;
- Tenure deliberately covers four brackets: "within one year / one to two years / two to three years / over three years" (for question 8);
- Several resigned employees (leave_date is not null, for questions 2/6 etc.);
- Salary is generated month by month based on "base salary in the year of hire + fixed annual raise amount",
  each employee's annual raise amount is different, so the ranking for question 9 "top 10 with largest raise" is unique;
- Deliberately delete one month's salary record for an active employee (for question 10 "salary arrears");
- All dates are generated relative to "today", with a fixed random seed of 42, ensuring reproducibility.

reference.py computes expected answers directly on these in-memory structures,
and compares them with the SQL execution results generated by the Agent to ensure semantic consistency.
"""

import random
from datetime import date, timedelta

# ---- Business Constants ----
DEPARTMENTS = ["R&D Department", "Sales Department", "Marketing Department", "Finance Department", "Human Resources Department"]
# Base salaries by department
DEPT_BASE = {"R&D Department": 15000, "Sales Department": 12000, "Marketing Department": 11000, "Finance Department": 12000, "Human Resources Department": 10000}

_SURNAMES = list("Zhao Qian Sun Li Zhou Wu Zheng Wang Feng Chen Chu Wei Jiang Shen Han Yang Zhu Qin You Xu He Lv Shi Zhang Kong Cao Yan Hua Jin Wei Tao Jiang")
_GIVEN = list("Wei Fang Na Xiu Ying Min Jing Li Qiang Lei Jun Yang Yong Yan Jie Juan Tao Ming Chao Xia Ping Gang Gui Xiang Jian Hua Zhi Qiang Xiao Dong Chun Mei Guo Dong Xue Song")


def _first_of_month(d: date) -> date:
    return date(d.year, d.month, 1)


def _add_month(d: date) -> date:
    """Return the 1st of the next month (d must be the 1st of a month)."""
    if d.month == 12:
        return date(d.year + 1, 1, 1)
    return date(d.year, d.month + 1, 1)


def _month_key(d: date) -> str:
    return f"{d.year:04d}-{d.month:02d}"


def generate(today: date | None = None):
    """Generate and return two list[dict]: (employees, salaries)."""
    if today is None:
        today = date.today()
    rng = random.Random(42)

    cur_month = _first_of_month(today)

    # Tenure brackets (day intervals relative to today), ensuring each bracket has people for question 8
    # bucket: (count, min_days, max_days)
    tenure_plan = [
        (8, 30, 360),      # Within one year of hire
        (8, 370, 720),     # One to two years
        (8, 740, 1080),    # Two to three years
        (16, 1100, 1900),  # Over three years
    ]

    employees = []
    emp_id = 0
    for count, dmin, dmax in tenure_plan:
        for _ in range(count):
            emp_id += 1
            days = rng.randint(dmin, dmax)
            hire_date = today - timedelta(days=days)
            dept = rng.choice(DEPARTMENTS)
            level = rng.randint(3, 9)
            name = rng.choice(_SURNAMES) + rng.choice(_GIVEN)
            employees.append({
                "emp_id": emp_id,
                "name": name,
                "department": dept,
                "level": level,
                "hire_date": hire_date,
                "leave_date": None,  # All active initially, then select some to resign
            })

    # Select about 6 employees with tenure >3 years to resign, with resignation dates within the past ~2 years
    senior = [e for e in employees if (today - e["hire_date"]).days > 1100]
    for e in rng.sample(senior, 6):
        # Resignation date = 60~700 days before today, and at least 200 days after hire
        leave = today - timedelta(days=rng.randint(60, 700))
        if (leave - e["hire_date"]).days < 200:
            leave = e["hire_date"] + timedelta(days=200)
        # Align to month end for monthly salary consistency
        e["leave_date"] = leave

    # Set a "base salary in the year of hire" and a "fixed annual raise amount" (different for each employee)
    for e in employees:
        e["_start_base"] = (
            DEPT_BASE[e["department"]] + e["level"] * 2000 + (e["emp_id"] % 7) * 300
        )
        # Raise amount strictly increases with emp_id, ensuring unique ranking for question 9 (no ties)
        e["_annual_raise"] = 400 + e["emp_id"] * 45

    # Designate one active, long-tenured employee as the "obvious raise champion" (top of question 9)
    big_raiser = next(
        e for e in employees
        if e["leave_date"] is None and (today - e["hire_date"]).days > 700
    )
    big_raiser["_annual_raise"] = 12000  # Far higher than others
    big_raiser["_is_big_raiser"] = True

    # ---- Generate monthly salaries ----
    salaries = []
    for e in employees:
        hire_m = _first_of_month(e["hire_date"])
        end_m = _first_of_month(e["leave_date"]) if e["leave_date"] else cur_month
        m = hire_m
        while m <= end_m:
            salary = e["_start_base"] + e["_annual_raise"] * (m.year - e["hire_date"].year)
            salaries.append({
                "emp_id": e["emp_id"],
                "pay_date": m,          # The 1st of each month represents that month's salary payment
                "salary": int(salary),
            })
            m = _add_month(m)

    # ---- Deliberately create a "salary arrears" case: an active employee missing a past month's salary (question 10) ----
    target = next(
        e for e in employees
        if e["leave_date"] is None and (today - e["hire_date"]).days > 800
    )
    # Delete the record from "6 months ago" (ensure it exists and is not the current month)
    missing_month = cur_month
    for _ in range(6):
        #6 months ago
        y, mo = missing_month.year, missing_month.month - 1
        if mo == 0:
            y, mo = y - 1, 12
        missing_month = date(y, mo, 1)
    before = len(salaries)
    salaries = [
        s for s in salaries
        if not (s["emp_id"] == target["emp_id"] and s["pay_date"] == missing_month)
    ]
    assert len(salaries) == before - 1, "Failed to delete target payroll record, please check seed logic"
    target["_owed_month"] = _month_key(missing_month)

    return employees, salaries


def create_db(conn, employees, salaries):
    """Create tables and insert data on the given SQLite connection."""
    cur = conn.cursor()
    cur.executescript(
        """
        DROP TABLE IF EXISTS employees;
        DROP TABLE IF EXISTS salaries;
        CREATE TABLE employees (
            emp_id      INTEGER PRIMARY KEY,
            name        TEXT    NOT NULL,
            department  TEXT    NOT NULL,
            level       INTEGER NOT NULL,   -- level, higher number means higher rank
            hire_date   TEXT    NOT NULL,   -- hire date YYYY-MM-DD
            leave_date  TEXT               -- leave date, NULL = active
        );
        CREATE TABLE salaries (
            emp_id      INTEGER NOT NULL,   -- references employees.emp_id
            pay_date    TEXT    NOT NULL,   -- pay date YYYY-MM-01 (one per month)
            salary      INTEGER NOT NULL,   -- monthly salary
            PRIMARY KEY (emp_id, pay_date)
        );
        """
    )
    cur.executemany(
        "INSERT INTO employees VALUES (?,?,?,?,?,?)",
        [
            (
                e["emp_id"], e["name"], e["department"], e["level"],
                e["hire_date"].isoformat(),
                e["leave_date"].isoformat() if e["leave_date"] else None,
            )
            for e in employees
        ],
    )
    cur.executemany(
        "INSERT INTO salaries VALUES (?,?,?)",
        [(s["emp_id"], s["pay_date"].isoformat(), s["salary"]) for s in salaries],
    )
    conn.commit()
