"""
Blender Python API (bpy) clip execution layer — the core of Experiment 5-6.

The book's approach emphasizes "code generation": the Proposer Agent does not click the GUI, but **generates a script that calls the Blender Python API**, where each editing operation (import/crop/subtitle/speed change/render) corresponds to a clear function call, and then executes it headlessly with `blender --background --python edit.py`.

This module has two exits:
  generate_bpy_script(source, plan, out_video) -> str
      Pure string generation, **does not depend on bpy**, any machine can produce this script (embodies code generation capability, can be manually verified, or copied to a machine with Blender installed for execution).
  render_with_blender(source, plan, out_video, script_path) -> str
      If `blender` is executable on this machine, writes the script and renders headlessly to produce the final video; otherwise raises an error for the caller to fall back.

Cropping is based on Blender's Video Sequence Editor (VSE): new_movie / new_sound import footage, frame_offset_start + frame_final_duration perform cropping, TEXT / SPEED effect strips overlay, FFMPEG (H.264+AAC) container rendering. API targets Blender 3.x / 4.x.
"""
import os
import shutil
import subprocess


def blender_available() -> bool:
    """Whether the local machine has the blender executable (determines whether to use Blender or ffmpeg when backend=auto)."""
    return shutil.which("blender") is not None


#  Generated bpy script template. All placeholders are injected via repr() to ensure valid Python literals.
_BPY_TEMPLATE = '''"""
This file is auto-generated by blender_editor.generate_bpy_script() (Experiment 5-6).
Execute: blender --background --python edit.py
It translates a clip plan into a sequence of Blender Video Sequence Editor (VSE) API calls.
"""
import os
import bpy

SRC = {src}
OUT = {out}
FPS = {fps}
START = {start}       # Target clip start (seconds)
END = {end}           # Target clip end (seconds)
SUBTITLE = {subtitle} # None or subtitle text
SLOWMO = {slowmo}     # None or slow-motion factor (factor>1 means slow down by factor)

scene = bpy.context.scene
scene.render.fps = FPS
scene.render.fps_base = 1.0

# Clear any existing sequence to ensure idempotency
if scene.sequence_editor:
    bpy.ops.sequencer.select_all(action='SELECT')
    bpy.ops.sequencer.delete()
se = scene.sequence_editor_create()

start_frame = int(round(START * FPS))
dur_frames = max(1, int(round((END - START) * FPS)))

# 1) Import movie + audio track (new_sound may raise RuntimeError on footage without audio, ignore it)
movie = se.sequences.new_movie(name="clip", filepath=SRC, channel=1, frame_start=1)
try:
    sound = se.sequences.new_sound(name="audio", filepath=SRC, channel=2, frame_start=1)
except RuntimeError:
    sound = None

# 2) Crop [START, END]: offset the head, then fix the duration
for strip in (movie, sound):
    if strip is None:
        continue
    strip.frame_offset_start = start_frame
    strip.frame_final_duration = dur_frames

top_channel = 3

# 3) Slow motion: SPEED effect strip (MULTIPLY mode, speed_factor = 1/factor)
if SLOWMO:
    speed = se.sequences.new_effect(
        name="slowmo", type='SPEED', channel=top_channel,
        frame_start=1, frame_end=1 + dur_frames, seq1=movie,
    )
    speed.use_default_fade = False
    speed.speed_control = 'MULTIPLY'
    speed.speed_factor = 1.0 / SLOWMO
    top_channel += 1
    # After slowing down, total frames are stretched by the factor
    render_dur = int(round(dur_frames * SLOWMO))
    movie.frame_final_duration = render_dur
else:
    render_dur = dur_frames

# 4) Subtitle: TEXT effect strip, bottom-centered with semi-transparent background
if SUBTITLE:
    txt = se.sequences.new_effect(
        name="subtitle", type='TEXT', channel=top_channel,
        frame_start=1, frame_end=1 + render_dur,
    )
    txt.text = SUBTITLE
    txt.font_size = 100
    txt.location = (0.5, 0.12)
    txt.align_x = 'CENTER'
    txt.align_y = 'BOTTOM'
    txt.use_box = True
    txt.box_color = (0.0, 0.0, 0.0, 0.6)

# 5) Render range + output as mp4 (H.264+AAC)
scene.frame_start = 1
scene.frame_end = render_dur

r = scene.render
r.image_settings.file_format = 'FFMPEG'
r.ffmpeg.format = 'MPEG4'
r.ffmpeg.codec = 'H264'
r.ffmpeg.audio_codec = 'AAC'
r.filepath = OUT
os.makedirs(os.path.dirname(OUT) or ".", exist_ok=True)

bpy.ops.render.render(animation=True)
print("BLENDER_RENDER_DONE", OUT)
'''


def _plan_fields(plan: dict):
    """Extract the fields needed for the bpy script from the clip plan."""
    start, end = float(plan["start"]), float(plan["end"])
    if end <= start:
        raise ValueError(f"Invalid clip interval: start={start} >= end={end}")
    effects = plan.get("effects", []) or []
    subtitle = None
    slowmo = None
    for eff in effects:
        etype = eff.get("type")
        if etype == "subtitle":
            subtitle = eff.get("text", "")
        elif etype == "slowmo":
            slowmo = float(eff.get("factor", 2.0))
    return start, end, subtitle, slowmo


def generate_bpy_script(source: str, plan: dict, out_video: str, fps: int = 30) -> str:
    """Render the clip plan into an executable Blender Python (bpy) script text (does not depend on bpy)."""
    start, end, subtitle, slowmo = _plan_fields(plan)
    return _BPY_TEMPLATE.format(
        src=repr(os.path.abspath(source)),
        out=repr(os.path.abspath(out_video)),
        fps=int(fps),
        start=repr(start),
        end=repr(end),
        subtitle=repr(subtitle),
        slowmo=repr(slowmo),
    )


def write_bpy_script(source: str, plan: dict, out_video: str,
                     script_path: str, fps: int = 30) -> str:
    """Generate bpy script and write to disk (produced regardless of backend, as a code generation artifact)."""
    script = generate_bpy_script(source, plan, out_video, fps=fps)
    os.makedirs(os.path.dirname(script_path) or ".", exist_ok=True)
    with open(script_path, "w") as f:
        f.write(script)
    return script_path


def render_with_blender(source: str, plan: dict, out_video: str,
                        script_path: str, fps: int = 30) -> str:
    """Write bpy script and execute headlessly with `blender --background --python` to produce the final video."""
    if not blender_available():
        raise RuntimeError(
            "Blender backend specified, but blender executable not found.\n"
            "  After installation, ensure `blender --version` works: https://www.blender.org/download/\n"
            "  Or use --backend ffmpeg instead."
        )
    write_bpy_script(source, plan, out_video, script_path, fps=fps)
    os.makedirs(os.path.dirname(out_video) or ".", exist_ok=True)
    proc = subprocess.run(
        ["blender", "--background", "--python", script_path],
        capture_output=True, text=True,
    )
    if proc.returncode != 0 or not os.path.exists(out_video):
        tail = "\n".join(proc.stderr.strip().splitlines()[-12:])
        raise RuntimeError(
            f"Blender rendering failed (exit={proc.returncode}）：\n{tail}\n"
            f"  You can manually check the generated script:{script_path}"
        )
    return out_video


if __name__ == "__main__":
    #  Zero-dependency self-check: print a sample bpy script "with cropping + subtitle" (can be py_compile verified for syntax).
    demo_plan = {
        "start": 16.0,
        "end": 28.0,
        "effects": [{"type": "subtitle", "text": "SURFING"}],
    }
    print("# blender available:", blender_available())
    print("# ---- generated edit.py ----")
    print(generate_bpy_script("output/source.mp4", demo_plan, "output/final.mp4"))
