"""
Video editing execution layer (dual backend).

The core of Experiment 5-6 in the book is "code generation": the Proposer Agent generates a script that calls the Blender Python API
(bpy) to perform editing. Therefore, this layer has two backends:

  - blender: translates the editing plan into a bpy script, using `blender --background --python` for headless rendering
             (see blender_editor.py) — the original approach in the book, requires Blender installation;
  - ffmpeg : uses ffmpeg to perform equivalent trimming/subtitles/slow motion, single binary, CI-friendly, verified locally.

apply_edit(..., backend=) unified entry: backend="auto" uses bpy if Blender is installed, otherwise falls back to
ffmpeg. **Regardless of the backend, the bpy script generated by Proposer is saved to disk (output/edit.py)**,
reflecting the core of "generating Blender Python API code", facilitating manual review or execution on another machine.

Supported operations:
  - trim       clips [start, end] segment
  - subtitle   overlays subtitles on the segment
  - slowmo     slow motion (slows down to factor times the duration)
All operations ultimately produce a standard mp4 (H.264 + AAC).
"""
import os

from blender_editor import blender_available, render_with_blender, write_bpy_script
from ffmpeg_utils import find_font, run


def _esc(text: str) -> str:
    """Escape special characters in drawtext/subtitles text."""
    return text.replace("\\", "\\\\").replace(":", r"\:").replace("'", r"\'")


def apply_edit(source: str, plan: dict, out_path: str,
               backend: str = "auto", script_path: str = None) -> str:
    """
    Generate the final video according to the editing plan.

    Plan structure (produced by Proposer Agent):
      {
        "start": float,          # Target segment start (seconds)
        "end": float,            # Target segment end (seconds)
        "effects": [             # Optional effects list
          {"type": "subtitle", "text": "..."},
          {"type": "slowmo", "factor": 2.0}
        ]
      }

    backend:
      "auto"    Use bpy if Blender is installed, otherwise fallback to ffmpeg (default).
      "blender" Force headless rendering with Blender bpy (error if Blender not installed).
      "ffmpeg"  Force editing with ffmpeg.

    Regardless of backend, the bpy script generated by Proposer is written to script_path
    (default: edit.py in the out directory), as the output of "generating Blender API code".
    Returns the path to the final video.
    """
    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    if script_path is None:
        script_path = os.path.join(os.path.dirname(out_path) or ".", "edit.py")

    #  Always output bpy scripts: this is exactly the implementation of "Proposer generates Blender scripts" in the book.
    write_bpy_script(source, plan, out_path, script_path)

    use_blender = backend == "blender" or (backend == "auto" and blender_available())
    if use_blender:
        return render_with_blender(source, plan, out_path, script_path)
    if backend == "blender":  #  Explicitly requires Blender but it is not installed
        return render_with_blender(source, plan, out_path, script_path)  #  Throw clear error
    return _apply_edit_ffmpeg(source, plan, out_path)


def _apply_edit_ffmpeg(source: str, plan: dict, out_path: str) -> str:
    """ffmpeg backend: crop/subtitle/slow motion equivalent to bpy scripts, producing H.264+AAC mp4."""
    start, end = float(plan["start"]), float(plan["end"])
    if end <= start:
        raise ValueError(f"Clip range invalid: start={start} >= end={end}")

    effects = plan.get("effects", []) or []
    vf_chain = []          #  video filter chain
    af_chain = []          # audio filter chain
    font = find_font()

    for eff in effects:
        etype = eff.get("type")
        if etype == "subtitle":
            txt = _esc(eff.get("text", ""))
            opts = [f"text='{txt}'", "fontsize=52", "fontcolor=white",
                    "x=(w-text_w)/2", "y=h-text_h-50",
                    "box=1", "boxcolor=black@0.6", "boxborderw=16"]
            if font:
                opts.insert(0, f"fontfile={font}")
            vf_chain.append("drawtext=" + ":".join(opts))
        elif etype == "slowmo":
            factor = float(eff.get("factor", 2.0))
            vf_chain.append(f"setpts={factor}*PTS")
            # atempo only supports 0.5~2.0, use 1/factor to slow down audio.
            af_chain.append(f"atempo={max(0.5, min(1.0, 1.0 / factor))}")

    cmd = ["ffmpeg", "-y", "-ss", f"{start:.3f}", "-to", f"{end:.3f}", "-i", source]
    if vf_chain:
        cmd += ["-vf", ",".join(vf_chain)]
    if af_chain:
        cmd += ["-af", ",".join(af_chain)]
    cmd += ["-c:v", "libx264", "-c:a", "aac", "-pix_fmt", "yuv420p", out_path]

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    run(cmd, desc="ffmpeg clip")
    return out_path


# --------------------------------------------------------------------------- #
# Blender backend description
# --------------------------------------------------------------------------- #
# Real Blender bpy script generation and headless rendering are implemented in blender_editor.py:
#   - generate_bpy_script(): Translates the clip plan into a bpy script (new_movie / crop /
#     TEXT / SPEED / render）——that is, "Proposer generates Blender script" in the book;
#   - render_with_blender(): Execute headlessly with `blender --background --python edit.py`.
# apply_edit(backend="blender") follows this path; backend="auto" (default) when Blender is not installed
#  Fallback to the ffmpeg backend of this file. The core "two-step Vision localization + proposer-verifier" is decoupled from the execution layer,
# Two backends share the same clip plan (plan), agents.py / demo.py do not need to change logic for switching backends.
