"""
Phase 4: Conversational Sentencing Suggestion Agent.

Use "case prototype + hierarchical factor importance" as decision logic:
  1. Extract known factors from user's colloquial description (reuse extractor, including charge determination);
  2. According to the **global factor importance order**, identify missing but important factors and generate guided follow-up questions;
  3. After information is complete, **match the case to the nearest case prototype**;
  4. Use LLM to organize the prototype's statistical data (typical sentencing range, defining key factors) into a coherent, explainable Chinese suggestion with case support (with legal disclaimer).

All sentencing numbers come from prototype statistics; LLM is only responsible for "explaining the numbers clearly", not fabricating them.
"""
from config import MODEL, get_client
from archetypes import nearest_archetype
from discovery import all_factors

DISCLAIMER = (
    "【Disclaimer】This response is automatically generated by a statistical model in a teaching experiment, for demonstration purposes only"
    "The technique of 'extracting tacit knowledge from structured data' does not constitute any legal advice. Actual case sentencing is affected by"
    "numerous factors such as legal provisions, judicial interpretations, region, and specific circumstances. Please consult a professional lawyer."
)


class LegalAdvisorAgent:
    def __init__(self, schema, model):
        self.schema = schema
        self.model = model  # archetypes.fit() output model
        self.client = get_client()
        self._factor = {f["key"]: f for f in all_factors(schema)}

    # --- Step 1: Extract known factors ---
    def extract_known(self, case_text):
        from extractor import extract_one
        return extract_one(case_text, schema=self.schema, client=self.client)

    # --- Step 2: Ask for missing important factors in order of global importance ---
    def missing_important_questions(self, known):
        questions, asked = [], set()
        for item in self.model["global_importance"]:
            col = item["feature"]
            # Parse factor key from column name (skip charge dimension — already determined)
            if col.startswith("charge="):
                continue
            key = col.split(":", 1)[1].split("=", 1)[0]
            if key in asked or key not in known:
                continue
            if known.get(key) is None:  # This factor applies to this charge but user has not provided it
                f = self._factor.get(key, {})
                questions.append({
                    "factor": key,
                    "name_cn": f.get("name_cn", key),
                    "importance": item["score"],
                    "question": f.get("question") or f"Please provide:{f.get('name_cn', key)}？",
                })
                asked.add(key)
        return questions

    # --- Step 3+4: Match nearest prototype and give suggestion ---
    def advise(self, known):
        arch, dist = nearest_archetype(self.model, known)
        m = arch["months"]
        defining = "；".join(
            f"{d['label']}（{d['direction']}, typical {d['typical']}）"
            for d in arch["defining"][:4]
        )
        evidence = (
            f"- Matched case prototype #{arch['id']}（{arch['charge']}, this prototype contains {arch['size']} cases),"
            f"Match distance {dist:.2f}\n"
            f"- Typical sentencing for this prototype: median {m['median']:.0f} months, range {m['min']:.0f}~{m['max']:.0f} months\n"
            f"- Key factors defining this prototype:{defining}"
        )
        known_desc = self._describe_known(known)

        system = (
            "You are a rigorous judicial data analysis assistant. Below is a data-driven model's match of a case to a"
            "'case prototype' and its statistics (numbers are from the model, do not modify). Please write a sentencing reference in Chinese within 160 characters"
            "that is clear and logical: first state the matched prototype and its typical sentencing range, then explain how the key factors shared between this case and the"
            "prototype affect the outcome. Do not fabricate numbers not given by the model, do not make definitive promises,"
            "do not repeat the disclaimer (the system will attach it separately)."
        )
        user = f"Known factors of this case:\n{known_desc}\n\nModel match basis:\n{evidence}"
        resp = self.client.chat.completions.create(
            model=MODEL, temperature=0.3,
            messages=[{"role": "system", "content": system},
                      {"role": "user", "content": user}],
        )
        return arch, resp.choices[0].message.content.strip() + "\n\n" + DISCLAIMER

    def _describe_known(self, known):
        parts = [f"Charge:{known.get('charge')}"]
        for key, v in known.items():
            if key == "charge":
                continue
            f = self._factor.get(key, {})
            if v is None:
                tag = "Unknown"
            elif isinstance(v, bool):
                tag = "Yes" if v else "No"
            else:
                tag = str(v)
            parts.append(f"{f.get('name_cn', key)}：{tag}")
        return "\n".join("  " + p for p in parts)
