"""
Synthesize a small-sample, multi-charge criminal judgment dataset.

CAIL2018 (real target dataset) is too large (millions of entries) to distribute with the repository; this experiment includes a
small offline sample covering three charges: theft, intentional injury, and fraud.

Each case contains:
  - `charge`  charge (known during generation, for reference only; the extraction phase will be determined by the LLM itself);
  - `fact`    a natural language description of the judgment facts;
  - `gold`    the ground truth factors used during generation (for manual verification only; extraction does not rely on it);
  - `label_months`  sentence length (months), generated by a "known" sentencing formula plus noise.

Key point: **Factors are "written" into the case text during generation, and then "read back" from the text during the discovery phase**.
The field names (English keys) used for generation only serve this file; the downstream factor discovery does not depend on them at all—during the discovery phase,
the LLM is allowed to freely summarize factors, so the learned patterns come from the data itself, not from the prior field list here.

Real migration: Replace this file with one that reads `data_*.json` from CAIL2018 (each line containing `fact`,
`meta.term_of_imprisonment`, and `meta.accusation`), and output a `cases.jsonl` with the same structure.
"""
import json
import math
import os
import random

random.seed(42)

DATA_DIR = os.path.join(os.path.dirname(__file__), "data")
OUT_PATH = os.path.join(DATA_DIR, "cases.jsonl")

NAMES = list("Zhao Qian Sun Li Zhou Wu Zheng Wang Feng Chen Chu Wei Jiang Shen Han Yang Zhu Qin You Xu He Lv Shi Zhang Kong Cao Yan Hua Jin Wei Tao Jiang Qi Xie Zou")
LOCATIONS = ["a certain residential area", "a certain shopping mall", "a certain office building", "a certain vegetable market", "a certain mobile phone store", "a certain electric vehicle shed", "a certain internet cafe"]


# ---------------------------------------------------------------------------
# theft
# ---------------------------------------------------------------------------
def gen_theft(i: int) -> dict:
    amount = int(round(random.uniform(1500, 400000), -1))
    f = {
        "prior_record": random.random() < 0.5,
        "surrender": random.random() < 0.45,
        "restitution": random.random() < 0.5,
        "confession": random.random() < 0.6,
        "burglary": random.random() < 0.45,
        "carry_weapon": random.random() < 0.25,
        "gang": random.random() < 0.4,
    }
    m = -18 + 5.2 * math.log(amount)
    m += f["prior_record"] * 11 + f["burglary"] * 7 + f["carry_weapon"] * 5 + f["gang"] * 3
    m += -f["surrender"] * 9 - f["restitution"] * 6 - f["confession"] * 3
    m += random.gauss(0, 1.2)
    months = int(max(1, min(180, round(m))))

    name = "the defendant" + random.choice(NAMES) + "a certain"
    prior = "had been previously sentenced for theft and committed the crime again after release, constituting a recidivist." if f["prior_record"] else "had no prior criminal record."
    scene = f"climbed through a window into the victim's{random.choice(LOCATIONS)}residence" if f["burglary"] else f"inside{random.choice(LOCATIONS)}in"
    weapon = ", carrying a dagger during the crime" if f["carry_weapon"] else ""
    gang = "in collusion with others" if f["gang"] else "alone"
    surrender = "voluntarily surrendered to the public security authorities after the incident," if f["surrender"] else "was later arrested by the public security authorities,"
    restitution = "has fully refunded the stolen money and obtained forgiveness." if f["restitution"] else "the stolen money has been squandered and not refunded."
    confession = "pleaded guilty and accepted punishment in court." if f["confession"] else "denied the allegations in court."
    fact = (
        f"{name}, male.{prior}after trial, it is established that:{name}{gang}{scene}{weapon}stole another person's property,"
        f"Appraised value of RMB{amount}yuan.{surrender}{restitution}{confession}"
    )
    return {"id": f"theft_{i:02d}", "charge": "Theft", "fact": fact,
            "gold": {"amount": amount, **f}, "label_months": months}


# ---------------------------------------------------------------------------
# Intentional injury
# ---------------------------------------------------------------------------
_INJURY_BASE = {"Minor injury": 2.0, "Mild injury": 12.0, "Severe injury": 40.0}


def gen_assault(i: int) -> dict:
    injury = random.choice(["Minor injury", "Minor injury", "Mild injury", "Mild injury", "Severe injury"])
    f = {
        "prior_record": random.random() < 0.35,
        "surrender": random.random() < 0.4,
        "restitution": random.random() < 0.55,  #Compensation and forgiveness carry significant weight in injury cases
        "confession": random.random() < 0.6,
        "injury_level": injury,
        "armed": random.random() < 0.45,
        "premeditated": random.random() < 0.3,
        "gang": random.random() < 0.35,
    }
    m = _INJURY_BASE[injury]
    m += f["prior_record"] * 8 + f["armed"] * 10 + f["premeditated"] * 8 + f["gang"] * 4
    m += -f["surrender"] * 6 - f["restitution"] * 10 - f["confession"] * 3
    m += random.gauss(0, 1.0)
    months = int(max(1, min(180, round(m))))

    name = "the defendant" + random.choice(NAMES) + "a certain"
    prior = "Previously sentenced for affray, a recidivist." if f["prior_record"] else "Generally good behavior, no prior criminal record."
    plan = "Due to long-standing grievances and premeditation," if f["premeditated"] else "After a quarrel over trivial matters,"
    gang = "Mobilized multiple people" if f["gang"] else "Held"
    weapon = ("Armed (with a machete)" if f["armed"] else "Unarmed") if not f["gang"] else ("And armed" if f["armed"] else "")
    injury_desc = {"Minor injury": "Identified as minor injury", "Mild injury": "Identified as mild injury level 2", "Severe injury": "Identified as severe injury level 2"}[injury]
    surrender = "Voluntarily surrendered after the incident," if f["surrender"] else "Fled the scene after the crime, later arrested,"
    restitution = "Compensated the victim and obtained forgiveness." if f["restitution"] else "Did not compensate the victim."
    confession = "pleaded guilty and accepted punishment in court." if f["confession"] else "Pleaded self-defense in court."
    fact = (
        f"{name}, male.{prior}after trial, it is established that:{name}{plan}{gang}{weapon}Assaulted the victim,"
        f"Causing them{injury_desc}。{surrender}{restitution}{confession}"
    )
    return {"id": f"assault_{i:02d}", "charge": "Intentional injury", "fact": fact,
            "gold": f, "label_months": months}


# ---------------------------------------------------------------------------
# Fraud
# ---------------------------------------------------------------------------
def gen_fraud(i: int) -> dict:
    amount = int(round(random.uniform(8000, 800000), -1))
    scam = random.choice(["Telecommunications network", "Telecommunications network", "Contract", "Ordinary"])
    victims = random.randint(1, 40) if scam == "Telecommunications network" else random.randint(1, 5)
    f = {
        "prior_record": random.random() < 0.35,
        "surrender": random.random() < 0.4,
        "restitution": random.random() < 0.45,
        "confession": random.random() < 0.6,
        "scam_type": scam,
        "victim_count": victims,
        "gang": random.random() < 0.5,
    }
    m = -22 + 6.0 * math.log(amount)
    m += f["prior_record"] * 10 + f["gang"] * 4
    m += {"Telecommunications network": 8.0, "Contract": 3.0, "Ordinary": 0.0}[scam]
    m += math.log(victims + 1) * 3.0
    m += -f["surrender"] * 8 - f["restitution"] * 7 - f["confession"] * 3
    m += random.gauss(0, 1.2)
    months = int(max(1, min(180, round(m))))

    name = "the defendant" + random.choice(NAMES) + "a certain"
    prior = "Had been sentenced to prison for fraud, a recidivist." if f["prior_record"] else "No prior criminal record."
    method = {
        "Telecommunications network": f"By means of telecommunication networks such as phone calls and text messages, fabricated investment projects to defraud{victims}victims",
        "Contract": "During the process of signing and performing contracts, defrauded victims using false identities and fabricated performance capabilities",
        "Ordinary": "Under the pretext of helping with affairs, fabricated facts to defraud victims",
    }[scam]
    gang = "In collusion with others, formed a gang," if f["gang"] else ""
    surrender = "Voluntarily surrendered after the incident," if f["surrender"] else "Later apprehended by the public security authorities,"
    restitution = "Has fully refunded all stolen money." if f["restitution"] else "Stolen money not recovered."
    confession = "pleaded guilty and accepted punishment in court." if f["confession"] else "Denied the intent to defraud in court."
    fact = (
        f"{name}, male.{prior}after trial, it is established that:{name}{gang}{method}Money,"
        f"Defrauded property totaling RMB{amount}yuan.{surrender}{restitution}{confession}"
    )
    return {"id": f"fraud_{i:02d}", "charge": "Fraud", "fact": fact,
            "gold": {"amount": amount, **f}, "label_months": months}


def main():
    os.makedirs(DATA_DIR, exist_ok=True)
    cases = []
    for i in range(1, 25):   # 24 Theft
        cases.append(gen_theft(i))
    for i in range(1, 23):   # 22 Intentional Injury
        cases.append(gen_assault(i))
    for i in range(1, 21):   # 20 Fraud -> Total 66 items
        cases.append(gen_fraud(i))
    random.shuffle(cases)

    with open(OUT_PATH, "w", encoding="utf-8") as fh:
        for c in cases:
            fh.write(json.dumps(c, ensure_ascii=False) + "\n")

    months = [c["label_months"] for c in cases]
    print(f"Generated {len(cases)} cases (Theft/Intentional Injury/Fraud) -> {OUT_PATH}")
    print(f"Sentencing range: {min(months)}~{max(months)} months, mean {sum(months)/len(months):.1f}")


if __name__ == "__main__":
    main()
