"""
Generate two real chart PNGs from the data in the paper, place them in Slidev's public/ directory,
for direct reference by the slides generated by Proposer (meeting the requirement of "at least 3 original charts", while
allowing the Reviewer's Vision check to truly evaluate whether "image sizes are appropriate").

These charts are drawn from the numbers in the paper body using matplotlib, and are programmatic reproductions of the
paper's original charts, not fabricated.
"""
import os
import matplotlib

matplotlib.use("Agg")  # No display environment
import matplotlib.pyplot as plt

PUBLIC_DIR = os.path.join(os.path.dirname(__file__), "slidev_workspace", "public")


def make_speedup_bar(path):
    """Figure 1: End-to-end speedup of FlashAttention relative to standard implementation (numbers from Section 4 of the paper)."""
    labels = ["BERT-large\n(seq 512)", "GPT-2\n(seq 1K)", "Long-Range\nArena"]
    speedups = [1.15, 3.0, 2.4]
    fig, ax = plt.subplots(figsize=(6, 3.4), dpi=150)
    bars = ax.bar(labels, speedups, color=["#4C72B0", "#DD8452", "#55A868"])
    ax.axhline(1.0, color="gray", linestyle="--", linewidth=1, label="baseline (1x)")
    ax.set_ylabel("Speedup vs. standard")
    ax.set_title("FlashAttention End-to-End Speedup")
    for b, v in zip(bars, speedups):
        ax.text(b.get_x() + b.get_width() / 2, v + 0.05, f"{v}x",
                ha="center", va="bottom", fontweight="bold")
    ax.set_ylim(0, 3.5)
    ax.legend(loc="upper left", fontsize=8)
    fig.tight_layout()
    fig.savefig(path, bbox_inches="tight")
    plt.close(fig)


def make_memory_hierarchy(path):
    """Figure 2: Bandwidth comparison of GPU memory hierarchy (table from Section 2 of the paper, log scale)."""
    levels = ["SRAM\n(on-chip)", "HBM\n(main GPU)", "CPU DRAM"]
    bandwidth = [19000, 1750, 12.8]  # GB/s
    fig, ax = plt.subplots(figsize=(6, 3.4), dpi=150)
    bars = ax.bar(levels, bandwidth, color=["#C44E52", "#8172B3", "#937860"])
    ax.set_yscale("log")
    ax.set_ylabel("Bandwidth (GB/s, log scale)")
    ax.set_title("GPU Memory Hierarchy (A100)")
    for b, v in zip(bars, bandwidth):
        ax.text(b.get_x() + b.get_width() / 2, v * 1.15,
                f"{v:g}", ha="center", va="bottom", fontweight="bold")
    fig.tight_layout()
    fig.savefig(path, bbox_inches="tight")
    plt.close(fig)


def generate_all():
    os.makedirs(PUBLIC_DIR, exist_ok=True)
    f1 = os.path.join(PUBLIC_DIR, "speedup_bar.png")
    f2 = os.path.join(PUBLIC_DIR, "memory_hierarchy.png")
    make_speedup_bar(f1)
    make_memory_hierarchy(f2)
    return {
        "/speedup_bar.png": "FlashAttention end-to-end speedup bar chart (BERT 1.15x / GPT-2 3x / LRA 2.4x)",
        "/memory_hierarchy.png": "A100 GPU memory hierarchy bandwidth comparison (SRAM 19TB/s / HBM ~1.75TB/s / DRAM 12.8GB/s, log scale)",
    }


if __name__ == "__main__":
    print(generate_all())
