"""
Slidev Renderer: Actually renders the slides.md generated by Proposer into "one PNG per page".

This is the key to this experiment—the reason the Reviewer can see "new information" that the Proposer cannot see
is precisely because we actually run the code and render pixel-level screenshots.

Implementation: Call the locally installed Slidev CLI
    npx slidev export slides.md --format png --output <dir> --timeout 60000
Slidev's PNG export uses playwright-chromium under the hood to open each page and take a screenshot.
"""
import glob
import os
import shutil
import subprocess

WORKSPACE = os.path.join(os.path.dirname(__file__), "slidev_workspace")


class RenderError(RuntimeError):
    pass


def render_slides(slides_md: str, out_subdir: str) -> list[str]:
    """
    Write the slides_md text to the workspace and export it as page-by-page PNGs.

    Args:
        slides_md:  Complete Slidev markdown source code
        out_subdir: Output subdirectory name (e.g., 'proposer_iter1')

    Returns:
        List of absolute PNG paths sorted by page number.
    """
    os.makedirs(WORKSPACE, exist_ok=True)
    slides_path = os.path.join(WORKSPACE, "slides.md")
    with open(slides_path, "w", encoding="utf-8") as f:
        f.write(slides_md)

    out_dir = os.path.join(WORKSPACE, "exports", out_subdir)
    if os.path.exists(out_dir):
        shutil.rmtree(out_dir)
    os.makedirs(out_dir, exist_ok=True)

    # Slidev's PNG export will generate 1.png, 2.png ... in the output directory
    cmd = [
        "npx", "--no-install", "slidev", "export", "slides.md",
        "--format", "png",
        "--output", out_dir,
        "--timeout", "60000",
        "--dark", "false",
    ]
    env = dict(os.environ)
    # Let playwright use the chromium installed in the project (playwright-chromium in package.json)
    proc = subprocess.run(
        cmd, cwd=WORKSPACE, env=env,
        capture_output=True, text=True, timeout=600,
    )
    if proc.returncode != 0:
        raise RenderError(
            "Slidev export failed:\n"
            f"stdout:\n{proc.stdout[-2000:]}\n"
            f"stderr:\n{proc.stderr[-2000:]}"
        )

    pngs = sorted(
        glob.glob(os.path.join(out_dir, "*.png")),
        key=lambda p: _page_num(p),
    )
    if not pngs:
        raise RenderError(
            f"Slidev export produced no PNGs. stdout:\n{proc.stdout[-2000:]}"
        )
    return pngs


def _page_num(path: str) -> int:
    base = os.path.splitext(os.path.basename(path))[0]
    digits = "".join(ch for ch in base if ch.isdigit())
    return int(digits) if digits else 0


if __name__ == "__main__":
    # Self-check: render a minimal two-page slidev
    demo = """---
theme: default
---

# Hello Slidev

First page

---

# Second page

- Rendering self-check succeeded
"""
    paths = render_slides(demo, "selftest")
    print("Rendered PNGs:")
    for p in paths:
        print("  ", p)
