"""Subprocess Python sandbox: execute model-generated code in an isolated subprocess with a timeout.

Pre-installed sympy / numpy / scipy (installed along with this project's requirements).
The reason for using a subprocess instead of exec() is:
  1. Isolation: model code crashes / infinite loops do not affect the main process;
  2. Timeout: can forcibly kill code that runs too long;
  3. Clean namespace: each execution uses a fresh interpreter.
"""

import subprocess
import sys
import tempfile
import os

#Pre-injected code before execution: pre-import common math libraries for the model to use directly.
PREAMBLE = """
import math
import sympy
import numpy as np
import scipy
from sympy import *
"""


def run_python(code: str, timeout: int = 20) -> str:
    """Execute Python code in a subprocess sandbox, returning stdout/stderr text.

    Args:
        code: Python source code to execute (generated by the model).
        timeout: Timeout in seconds; the subprocess is terminated if exceeded.
    Returns:
        Execution output (combined stdout and stderr). The model should output results via print().
    """
    full_code = PREAMBLE + "\n" + code

    #Write to a temporary file and execute with the current interpreter (which has sympy/numpy/scipy installed).
    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".py", delete=False, encoding="utf-8"
    ) as f:
        f.write(full_code)
        path = f.name

    try:
        proc = subprocess.run(
            [sys.executable, path],
            capture_output=True,
            text=True,
            timeout=timeout,
            #Execute in a temporary directory to avoid accidentally reading/writing project files (still can access installed libraries).
            cwd=tempfile.gettempdir(),
        )
        out = proc.stdout
        if proc.stderr.strip():
            out += "\n[stderr]\n" + proc.stderr
        if not out.strip():
            out = "(The code produced no output; please remember to use print() to display results)"
        #Truncate overly long output to avoid blowing up the context.
        return out[:4000]
    except subprocess.TimeoutExpired:
        return f"[Error] Code execution timed out (exceeded {timeout} seconds); there may be an infinite loop or excessive computation."
    except Exception as e:  # noqa: BLE001
        return f"[Error] Execution failed: {e}"
    finally:
        try:
            os.unlink(path)
        except OSError:
            pass


if __name__ == "__main__":
    #Simple self-test
    print(run_python("from sympy import factorint; print(factorint(360))"))
    print(run_python("print(sum(1 for n in range(1,2025) if n%3 and n%5 and n%7))"))
